spring.application.name=sandbox-spei
spring.datasource.url=jdbc:h2:mem:sandbox_spei;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
